#---------------------------------------------------------------------
# Manifest File to create Ingress Rules for Hosts
#---------------------------------------------------------------------
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-hosts

spec:
  rules:
    - host: "www.pugachev.fun"
      http:
        paths:
          - pathType: Prefix
            path: "/nginx"
            backend:
              service:
                name: nginx-service
                port:
                  number: 80